builds:
- id: agentyesno
  binary: agentyesno
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - freebsd
    - openbsd
  goarch:
    - amd64
    - arm
    - arm64
  mod_timestamp: "{{ .CommitTimestamp }}"
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

checksum:
  name_template: "checksums.txt"
