builds:
- id: agentyesno
  binary: agentyesno
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - freebsd
    - openbsd
  goarch:
    - amd64
    - arm
    - arm64

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
